apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hermescontrol-api-hpa
  namespace: burguerspace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hermescontrol-api-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50